### ISSUE TITLE
Work through static analysis issues and ensure ember-try tests are passing

### ISSUE THREAD

**Issue by morgan** [caxiam/ember-tabular#37]

**Comment by Aaronfischer** [comment]
@morgan a few things after looking over this: 
* "Missing function expression name." -  ESLINT expects a named function instead of an anonymous function but ember requires this specific syntax, I also tried using arrow functions but that is not supported yet: https://github.com/babel/ember-cli-babel/issues/30#issuecomment-93808508
* "Similar code found in 1 other location" - ESLINT does not understand the requirements of ember's conventions (config properties on component/controller/route basis)

Still sifting through everything but that is what I've found so far specific to ember.
